---
output: 
  pdf_document:
    latex_engine: pdflatex # I installed https://yihui.name/tinytex/ instead of the recommended defaults
    template: cv-latex.tex
geometry: margin=.7in

title: "CV"
author: Richard Klein

fontawesome: yes
email: raklein22@gmail.com
github: raklein
# twitter: "@raklein3"
phone: "on request"
web: www.raklein.me
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---

# Positions
**Clinical Data Scientist** \hfill 2023-Present  
*Office of New Drugs, Food and Drug Administration, Silver Spring, Maryland*  

- Develop Safety Data Review Plans for New Drug Applications and analyze data from clinical trials for safety signals prior to drug approval

**Researcher** \hfill 2019-2023  
*Tilburg University, Department of Methodology and Statistics, Tilburg, the Netherlands*  

- Metascience research about bias in the publication process and reproducibility of results 

**Postdoctoral Researcher** \hfill 2018-2019  
*Université Grenoble Alpes, LIP/PC2S, Grenoble, France*  

- Social psychology research with an emphasis on methods and data science

# Education

**Ph.D. in Psychology** \hfill Aug 2017  
*University of Florida, Gainesville, FL*

**M.S. in Psychology** \hfill May 2014  
*University of Florida, Gainesville, FL*

**BS in Psychology, BS in Finance** \hfill May 2011  
*Pennsylvania State University, University Park, PA*

# Peer Reviewed Publications
(\* indicates undergraduate author)

Wicherts, J., **Klein, R. A.**, Swaans, S., Maassen, E., Stoevenbelt, A., ... & Ruffer, F. (2022). How to Protect Privacy in Open Data. *Nature Human Behaviour*. DOI: [https://doi.org/10.1038/s41562-022-01481-w](https://doi.org/10.1038/s41562-022-01481-w)

Kakinohana, R. K., **Klein, R. A.**, & Pilati, R. (2022). Does anchoring vary across cultures? Expanding the Many Labs analysis. *European Journal of Social Psychology*. DOI: [https://doi.org/10.1002/ejsp.2924](https://doi.org/10.1002/ejsp.2924)

Hoogeveen, S., Sarafoglou, A., Aczel, B., Aditya, Y., Alayan, A. J., ... **Klein, R. A.** ... & Nilsonne, G. (2022). A many-analysts approach to the relation between religiosity and well-being. *Religion, Brain & Behavior*. DOI: [https://doi.org/10.1080/2153599X.2022.2070255](https://doi.org/10.1080/2153599X.2022.2070255)

Krypotos, A. M., **Klein, R. A.**, & Jong, J. (2022). Resolving religious debates through a multiverse approach. *Religion, Brain & Behavior*. DOI: [https://doi.org/10.1080/2153599X.2022.2070261](https://doi.org/10.1080/2153599X.2022.2070261)

**Klein, R. A.**, Cook, C. L., Ebersole, C. R., Vitiello, C., Nosek, B. A., Hilgard, J., ... & Ratliff, K. A. (2022). Many Labs 4: Failure to replicate mortality salience effect with and without original author involvement. *Collabra: Psychology, 8*(1), 35271. DOI: [https://doi.org/10.1525/collabra.35271](https://doi.org/10.1525/collabra.35271)

Sarda, E., **Klein, R. A.**, Dujols, O., & IJzerman, H. (2021). Validation of the ISP131001 Sensor for Mobile Peripheral Body Temperature Measurement. *International Review of Social Psychology, 34*(1), 12. DOI: [http://doi.org/10.5334/irsp.409](http://doi.org/10.5334/irsp.409)

Moshontz, H., Ebersole, C. R., Weston, S. J., & **Klein, R. A.** (2021). A Guide for Many Authors: Writing Manuscripts in Large Collaborations. *Social and Personality Psychology Compass*. [https://doi.org/10.1111/spc3.12590](https://doi.org/10.1111/spc3.12590)

Vergara, R. C., Hernández, C., Jaume-Guazzini, F., Lindenberg, S., **Klein, R. A.**, & IJzerman, H. (2019). Development and Validation of the Social Thermoregulation and Risk Avoidance Questionnaire (STRAQ-1). *International Review of Social Psychology, 32*(1), 18. [http://doi.org/10.5334/irsp.222](http://doi.org/10.5334/irsp.222)

Conway, M. A., O'Shea, B., Redford, L., Pogge, G., **Klein, R. A.**, & Ratliff, K. A. (2019). Can Carelessness Be Captured? Assessing Careless Responding in Attitudes Toward Novel Stimuli. *Social Cognition, 37*(5), 468-498. [https://doi.org/10.1521/soco.2019.37.5.468](https://doi.org/10.1521/soco.2019.37.5.468)

**Klein, R. A.**, Vianello, M., Hasselman, F., Adams, B. G., Adams, R. B., Alper, S., … Nosek, B. A. (2018). Many Labs 2: Investigating variation in replicability across samples and settings. *Advances in Methods and Practices in Psychological Science, 1*(4), 443–490. [https://doi.org/10.1177/2515245918810225](https://doi.org/10.1177/2515245918810225)

- Research covered by [Nature](https://www.nature.com/articles/d41586-018-07474-y), [The Atlantic](https://www.theatlantic.com/science/archive/2018/11/psychologys-replication-crisis-real/576223/), and others.

Bastart, J., **Klein, R. A.**, IJzerman, H., (2018). Replication initiatives in psychology. *Oxford Bibliographies in Psychology*. [https://doi.org/10.1093/OBO/9780199828340-0212](https://doi.org/10.1093/OBO/9780199828340-0212)

Milfont, T. L., **Klein, R. A.** (2018). Replication and reproducibility in cross-cultural psychology. *Journal of Cross-Cultural Psychology, 49*(5), 735-750. [https://doi.org/10.1177/0022022117744892](https://doi.org/10.1177/0022022117744892)

Ebersole, C. R., Atherton, O. E., Belanger, A. L., Skulborstad, H. M., Allen, J. M., … **Klein, R. A.**, … Nosek, B. A. (2016). Many Labs 3: Evaluating participant pool quality across the academic semester via replication. *Journal of Experimental Social Psychology*. [https://doi.org/10.1016/j.jesp.2015.10.012](https://doi.org/10.1016/j.jesp.2015.10.012)

Lai, C. K., Skinner, A. L., Cooley, E., Murrar, S., Brauer, M., … **Klein, R. A.**, … Nosek, B. A. (2016). Reducing implicit racial preferences: II. Intervention effectiveness across time. *Journal of Experimental Psychology: General, 145*, 1001-1016. [https://doi.org/10.1037/xge0000179](https://doi.org/10.1037/xge0000179)

**Klein, R. A.**, Ratliff, K. A., Vianello, M., Adams, R. B., Jr., Bahník, S., Bernstein, M. J., Bocian, K., … Nosek, B. A. (2014). Data from investigating variation in replicability: A “many labs” replication project. *Journal of Open Psychology Data, 2*(1): e4. [http://dx.doi.org/10.5334/jopd.ad](http://dx.doi.org/10.5334/jopd.ad)

**Klein, R. A.**, Ratliff, K. A., Vianello, M., Adams, R. B., Jr., Bahník, S., Bernstein, M. J., Bocian, K., … Nosek, B. A. (2014). Theory building through replication: Response to commentaries on the “many labs” replication project. *Social Psychology, 45*(4): 307-310. [https://doi.org/10.1027/1864-9335/a000202](https://doi.org/10.1027/1864-9335/a000202)

**Klein, R. A.**, Ratliff, K. A., Vianello, M., Adams, R. B., Jr., Bahník, S., Bernstein, M. J., Bocian, K., … Nosek, B. A. (2014). Investigating variation in replicability: A "many labs" replication project.  *Social Psychology, 45*(3): 142-152. [https://doi.org/10.1027/1864-9335/a000178](https://doi.org/10.1027/1864-9335/a000178)  

- Research covered by [Nature](https://www.nature.com/news/psychologists-strike-a-blow-for-reproducibility-1.14232), [Science magazine](http://www.sciencemag.org/news/2013/11/second-look-psychology-experiments-offers-reassurance), [National Geographic](https://www.nationalgeographic.com/science/phenomena/2013/11/26/welcome-to-the-era-of-big-replication/), and others.

# Organized Conferences, Symposia, and Workshops

**Klein, R. A.**, Balzarini, R., IJzerman, H., Sarda, E., Kaufman, M. (2019). EASP Technology and Relationships Conference and Facebook+AdopteUnMec Hackathon. Annecy, France.  
[https://web.archive.org/web/20190916124841/https://techandrelationships.org/](https://web.archive.org/web/20190916124841/https://techandrelationships.org/)

**Klein, R. A.** (2019). Open Science Toolbox: Leveraging Methodological Reforms to Accelerate Research. Symposium organized for the International Convention of Psychological Science, Paris, France.  
Speakers: **Richard Klein**, Ben Jones, Lisa DeBruine, Niamh Stack.
[https://osf.io/tve2q/](https://osf.io/tve2q/)

IJzerman, H. I., Ric, F., **Klein, R. A.** (2018). RKTS Solid Science Training Workshop in Bordeaux, France.  
Speakers: Michèle Nuijten, Fieke Wagemans, Marco Perugini, **Richard Klein**, Kai Jonas, Frederik Aust, Benedict Jones.
[https://osf.io/gvkxn/](https://osf.io/gvkxn/)

**Klein, R. A.** (2014). Reproducibility in Psychology: Understanding and Improving Your Odds. Symposium organized for the annual meeting of the Society of Southeastern Social Psychologists, Athens, GA.  
Speakers: Gregory Webster, **Richard Klein**, Chris Martin.

# Talks

**Klein, R. A.** (2021). Privacy Risks in Open Datasets. Talk presented at the Metascience 2021 conference, organized online. Slides: [https://osf.io/b564v/](https://osf.io/b564v/) Video: [https://youtu.be/w40J0-Z6epU](https://youtu.be/w40J0-Z6epU)

**Klein, R. A.** (2020). Many Labs 4: Conducting replications of mortality salience with and without original author involvement. Talk presented at the Society for Personality and Social Psychology annual conference, New Orleans, Louisiana, USA. [https://osf.io/bgh48/](https://osf.io/bgh48/)

**Klein, R. A.** (2019). An Overview of Workflow Management: Using the Open Science Framework. Workshop presented as part of the Open Science Workshop, Grenoble, France. [https://osf.io/nxem8/](https://osf.io/nxem8/)

**Klein, R. A.** (2019). Welcome to the era of big psychology. Invited workshop presented as part of the Machine Learning: Applications to Clinical and Psychological Research Workshop, Rovereto, Italy. [https://github.com/raklein/presentation-rep-machine-learning-rovereto](https://github.com/raklein/presentation-rep-machine-learning-rovereto)

**Klein, R. A.** (2019). Many Labs 2: Investigating variation in replicability across sample and setting. Talk presented at the International Convention of Psychological Science, Paris, France. [https://github.com/raklein/presentation-icps2019-ml2](https://github.com/raklein/presentation-icps2019-ml2)

**Klein, R. A.** (2019). Walking through Many Labs 4 to show how R can make complex analyses easier. Workshop recorded for Pacific Lutheran University, Tacoma, Washington, USA.

**Klein, R. A.** (2019). Many Labs 2: Investigating replicability across samples and settings. Talk presented at the Society for Personality and Social Psychology annual conference, Portland, Oregon, USA. [https://github.com/raklein/presentation-spsp2019-ml2](https://github.com/raklein/presentation-spsp2019-ml2)

**Klein, R. A.** (2018). Many Labs 2: Investigating variation in replicability across samples and settings. Talk presented at the Integrity and Sharing of Science: Research Data seminar, Grenoble, France. [https://github.com/raklein/presentation-datadoct2018-ml2](https://github.com/raklein/presentation-datadoct2018-ml2)

**Klein, R. A.** (2018). Introduction to concepts in deep learning and cross-validation. Workshop session presented at the RKTS Solid Science Training Workshop in Bordeaux, France. [https://osf.io/ya2n8/](https://osf.io/ya2n8/)

**Klein, R. A.** (2018). Many Labs 2: Investigating variation in replicability across samples and settings. Talk presented at the 20th ESCON Transfer of Knowledge Conference, Cologne, Germany. [https://osf.io/vznpj/](https://osf.io/vznpj/)

**Klein, R. A.** (2015). Replication in psychology: How sensitive are our findings? Invited talk presented at the Victoria University of Wellington Psychology Colloquium Series, Wellington, New Zealand. [https://osf.io/m8u9b/](https://osf.io/m8u9b/)

**Klein, R. A.** (2015). Many Labs 2: Investigating variation in replicability across samples and settings. Invited talk presented at the 95th Annual Convention of the Western Psychological Association, Las Vegas, NV. [https://osf.io/43h9x/](https://osf.io/43h9x/)

**Klein, R. A.** (2014). Crowdsourcing research to increase reproducibility, generalizability, and accuracy. Talk presented at the annual meeting of the Society of Southeastern Social Psychologists, Athens, GA. [https://osf.io/qtr7a/](https://osf.io/qtr7a/)

# Discussion Panels

Baranski, E., Weston, S. (2019). Lifespan pre-conference open science discussion. Discussion panel presented at the Lifespan Preconference of the Society for Personality and Social Psychology annual conference, Portland, Oregon, USA.  
Panelists: Charles Ebersole, **Richard Klein**, Jessie Sun, Cassie Brandes, Alex Danvers, Ted Schwaba

Grahe, J., (2015). Emerging adulthood measured at multiple institutions: A new model to study emerging adulthood. Discussion panel presented at the Society for the Study of Emerging Adulthood 7th Biennial Conference, Miami, FL.  
Panelists: **Richard Klein**, Tanya Sharon, Scott Hall

**Klein, R. A.** (2015). Networking: Online and in-person. Talk and panel discussion presented at the Psychology Graduate Student Organization Professional Development Seminar, Gainesville, FL.

# Poster Presentations

**Klein, R. A.** (2017). *“Many labs” and communication in replication*. Poster presented at the Eighteenth Annual Meeting of the Society for Personality and Social Psychology, San Antonio, TX.

Bland, D.\*, Grahe, J., **Klein, R. A.** (2015). *Disgust sensitivity and judgements of intentions as part of the Many Labs 2 project*. Poster presented at the 95th Annual Convention of the Western Psychological Association, Las Vegas, NV.

Coddington, K.\*, Gervais, H.\*, Grahe, J., **Klein, R. A.** (2015). *Replication examining moral typecasting effects as part of the Many Labs 2 project*. Poster presented at the 95th Annual Convention of the Western Psychological Association, Las Vegas, NV.

Grisham, E.\*, Musselman, D.\*, Barnette, T.\*, Powers, M.\*, Gonzalez, G.\*, … **Klein, R. A.**, … Redford, L. (2015). *Implicit preference for White people over Black people decreases with repeated Implicit Association Tests (IATs)*. Poster presented at the Undergraduate Research Forum, University of Florida Psychology Department, Gainesville, FL

**Klein, R. A.**, Vianello, M., & Ratliff, K. A. (2015). *Attention checking the “Many Labs” participants: Did participant attention moderate the included effects?*. Poster presented at the Sixteenth Annual Meeting of the Society for Personality and Social Psychology, Long Beach, CA.

**Klein, R. A.**, & Ratliff, K. A. (2014). *Context effects in implicit and explicit evaluation*. Poster presented at the Fifteenth Annual Meeting of the Society for Personality and Social Psychology, Austin, TX.

Collisson, B. & **Klein, R. A.** (2012). *Personality correlates of social inference*. Poster presented at the Meeting of the Society of Southeastern Social Psychologists, Gainesville, FL.

# Research Experience

**Postdoctoral Researcher** \hfill 2019 - 2023  
*Metascience Group, Tilburg University*

- PIs: Dr. Jelte Wicherts, Dr. Marjan Bakker
-	Led a team of up to 22 members in identifying flaws in research processes and methods to ensure the accuracy and value of outputs and conclusions
-	Assessed privacy risks in 2K+ research datasets through analysis and evaluation to determine that 5-10% contained addressable privacy concerns
-	Delivered essential content matter to secure a €50,000 grant to develop and implement an R package and web application to automatically detect and prevent privacy risks
-	Created analysis protocols for multi-verse analysis of 100+ projects utilizing 1,000+ simultaneous analysis pipelines to create a more robust understanding of the data while reducing bias


**Postdoctoral Researcher** \hfill 2018 - 2019  
*Coregulation Lab, Université Grenoble Alpes*

- PI: Dr. Hans IJzerman
-	Conducted research on romantic couples to discover reciprocal trends in behavior predicting relationship satisfaction by employing surveys and physiological sensors paired with linear mixed effects models
-	Verified research methods and data throughout the lab group to bolster the value of published insights and outputs
-	Provided instruction to senior-level bachelor students in Introduction to Research and Data Analysis and master-level students on The Psychology of Performance 


**Research Coordinator** \hfill 2013 - 2017  
*Project Implicit, implicit.harvard.edu*

-	Strengthened overall performance by monitoring data quality, testing research tools, and debugging code across a site generating 90k visitors monthly 
-	Increased interactive user experience metrics and reduced attrition by up to 30% through innovative site changes and process improvements
-	Collaborated with developers to implement functional site changes based on user feedback and content performance to boost validity of study results
-	Liaised between development team, project managers, and leadership to communicate needs, capabilities, and feasibility of proposed projects or site changes resulting in greater clarity and understanding across groups


**Researcher** \hfill 2012 - 2017  
*Attitudes and Social Cognition Lab, University of Florida*

- PI: Dr. Kate Ratliff
-	Oversaw multiple large-scale projects by coordinating 270+ researchers across 33 countries 
-	Developed an innovative multi-lab research strategy testing the effectiveness of insights across international contexts by assessing 40+ foundational psychological theories
-	Designed, executed, and analyzed over 60 psychological experiments driving data from over 23k participants


**Undergraduate Research Assistant** \hfill 2011 - 2012  
*Social Vision and Interpersonal Perception Lab, Penn State*

- PI: Dr. Reginald Adams

# Teaching Experience

**Instructor**   
*Université Grenoble Alpes*

- Introduction à la Recherche et Analyse des Données  \hfill Spring 2019
  - Upper level undergraduate research methods course.

**Instructor**   
*University of Florida*

- PSY2012 - Introduction to Psychology (x2) \hfill Fall 2014, Summer 2015
  - Overall evaluation: 4.42/5

**Teaching Assistant**  
*University of Florida*

-	PSY4625 – Psychology of Pseudoscience \hfill Spring 2017
-	SOP4214C – Research Methods in Social Psychology \hfill Fall 2016
- PSY4930 – Psychology of Public Policy \hfill Summer 2014
- SOP3004 – Introduction to Social Psychology (x3) \hfill Fall 2013, Spring 2014, Spring 2015

**Teaching Assistant**  
*Pennsylvania State University*

- PSYCH105 – Psychology as a Science and Profession \hfill Spring 2012
- PSYCH261 – Introduction to the Psychology of Learning \hfill Spring 2012
-	PSYCH243 – Introduction To Well-Being And Positive Psychology (x2) \hfill Fall 2011, Spring 2012
- PSYCH100 – Introductory Psychology (x4) \hfill Fall 2011

# Supervised Theses

- Olivier Dujols, Doctoral Dissertation, Université Grenoble Alpes \hfill 2023 (expected)
- Donovan Ellis, Undergraduate Thesis, University of Florida, awarded Highest Distinction \hfill 2015

# Awards, Honors, Service

- Peer-reviewed for:
    + *Advances in Methods and Practices in Psychological Science*
    + *American Journal of Political Science*
    + *Collabra: Psychology*
    + *eLife*
    + *Frontiers in Psychology, Review Editor* \hfill 2017 - 2018
    + *Journal of Social Psychology*
    + *PLOS ONE*
    + *Social Cognition*
    + *Social Psychological and Personality Science*
    + *Templeton World Charity Foundation*
    + *The Spanish Journal of Psychology*
    + *The European Association of Social Psychology*
    + *Perspectives on Psychological Science*
    + *Psychological Science*
    + *The International Review of Social Psychology, Editorial Board* \hfill 2019 - 2020
- Open Science Fund Grant, Dutch Research Council (€50,000) \hfill 2021
- Commendation from the Society for the Improvement of Psychological Science \hfill 2020
- Served on SPSP Task Force implementing Transparency and Openness Promotion guidelines \hfill 2020
-	Gerber Social Psychology Outstanding Research Award ($1,000) \hfill 2016
-	Incubator Grant, Center for Open Science ($13,500) \hfill 2015
-	Travel Award, UF Department of Psychology ($500) \hfill 2015
-	Travel Award, UF College of Liberal Arts and Sciences ($300) \hfill 2015
-	Travel Award, Society for Personality and Social Psychology ($500) \hfill 2015
-	Advisory Board Member, CREP Project \hfill 2014 – 2016
-	Graduate School Fellowship, University of Florida ($80,000) \hfill 2012 – 2016
-	Dean’s List, Pennsylvania State University \hfill 2007 – 2011

# Relevant Skills

- **Statistical programs**: R/R Studio/RMarkdown, SPSS, JASP
- **Statistical techniques**: Linear/logistic/multiple regression, correlation, ANOVA, linear mixed models, factor analysis, meta-analysis, machine learning/deep learning
- **Other tools**: Open Science Framework, MS Excel/Word/PowerPoint, Google Sheets/Docs/Forms, Qualtrics Survey Software, Git/GitHub, SQL
- **Languages**: English (native), French (intermediate)